#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn -B clean install
          - mvn -B test
        after-script:
          # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
          - pipe: atlassian/checkstyle-report:0.3.0
        services:
          - docker
    - step:
        name: Code Quality Analysis
       - pipe: sonarsource/sonarcloud-scan:2.0.0
          variables:
          EXTRA_ARGS: -Dsonar.projectDescription=\"Project with sonarcloud-scan pipe\" -Dsonar.eslint.reportPaths=\"report.json\"
          SONAR_SCANNER_OPTS: -Xmx512m
          DEBUG: "true"
    - step:
        name: Integration Tests
        script:
          # Run integration tests
          - mvn verify -DskipUnitTests=false
        services:
          - docker
    - step:
        name: Security Scan
        script:
          # Run a security scan for sensitive data.
          - pipe: atlassian/git-secrets-scan:0.5.1
        services:
          - docker
    - step:
        name: Deploy to Staging
        deployment: staging
        script:
          - echo 'Deploying to staging environment'
          - pipe: atlassian/slack-notify:2.3.1
            variables:
              WEBHOOK_URL: 'https://hooks.slack.com/services/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'
              MESSAGE: 'Deploy to staging completed successfully'
        services:
          - docker
    - step:
        name: Deploy to Production
        deployment: production
        trigger: manual
        script:
          - echo 'Deploying to production environment'
          - pipe: atlassian/slack-notify:2.3.1
            variables:
              WEBHOOK_URL: 'https://hooks.slack.com/services/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'
              MESSAGE: 'Deploy to production completed successfully'
        services:
          - docker
